sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t tristanzhou/docker-react -f Dockerfile.dev .

script:
  - docker run tristanzhou/docker-react npm run test -- --coverage