sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t tristanzhou/docker-react -f Dockerfile.dev .

language: node_js
node_js:
  - "10.15.3"
script:
  - yarn test
  - docker run tristanzhou/docker-react npm run test -- --coverage